### ISSUE TITLE
🚀 Create Next.js App and Configure Eslint, Fonts, Husky, Docker and more 

### ISSUE THREAD

**Issue by learnforward2023** [learnforward2023/project-web#1]
## User Story (Why) 📑

**Epic** này bao gồm các tác vụ thiết lập và cấu hình để tạo ứng dụng Next.js cùng với việc thiết lập eslint để tìm lỗi code, định cấu hình phông chữ để có kiểu dáng nhất quán và tích hợp Husky để chạy một số command trước khi commit.

Và còn nhiều thứ khác 👍 

## What should I do? 🤔

- Create Next.js Application
- Configure Eslint
- Configure Fonts
- Integrate Husky

## What is the GOALs? 🤩

- **Efficient Next.js Setup**: Bắt đầu một dự án Next.js mới với cấu trúc được tổ chức tốt và có sẵn các tệp thiết yếu, giúp giảm thời gian và công sức thiết lập.
- **Code Quality Assurance**: Triển khai eslint với các quy tắc thích hợp để duy trì chất lượng mã nhất quán trong suốt dự án, giúp xác định và khắc phục sớm các vấn đề tiềm ẩn trong quá trình phát triển.
- **Consistent Styling**: Định cấu hình phông chữ để đảm bảo kiểu dáng hình ảnh nhất quán và hấp dẫn trên toàn bộ ứng dụng, nâng cao trải nghiệm người dùng và nhận diện thương hiệu.
- ...

# Tasks

- [ ] [Khởi tạo project NextJs bằng `create-next-app`](https://github.com/learnforward2023/project-web/commit/d58d34df36bfd20ce71a4569824e1d0e5e118a44)
- [ ] [Config `dependabot` để tự động cập nhật package nếu có phiên bản mới.](https://github.com/learnforward2023/project-web/commit/035eb0edb2dd0d254638f8509ed809e79ec605d4)
- [ ] [Update github workflow - eslint, thank-you-pr, open-ai-review, misspell & template](https://github.com/learnforward2023/project-web/commit/c3040e1729b869c0780c090b63e400202284f26a)
- [ ] [Add more rules for ESLint and fix automatically](https://github.com/learnforward2023/project-web/commit/44b2ac329d5495af82e1e5c6fcf6e9d2e9424aae)
- [ ] [Cài đặt ứng dụng chạy trên Docker](https://github.com/learnforward2023/project-web/commit/7dc48698135d64ea5698bfa0e40c90b4bd285ddd)
- [ ] [install lint-staged and config husky](https://github.com/learnforward2023/project-web/commit/d82b98e8d9a18939b8ee7c1cd7126acc8d4b4732)
